[variables]
HOST = "localhost"
DB_HOST = "mysql"
DB_PORT = "3306"
DB_NAME = "edelphi"
DB_USERNAME = "edelphi"
DB_PASSWORD = "password"
CLUSTER_PASSWORD = "railwaycluster123"
KEYCLOAK_REALM = "edelphi"
KEYCLOAK_RESOURCE = "edelphi-api"
KEYCLOAK_SECRET = "changeme-secret"
KEYCLOAK_URL = "http://keycloak:8080"
SMTP_HOST = "localhost"
SMTP_USERNAME = ""
SMTP_PASSWORD = ""
SMTP_PORT = "25"
SMTP_TLS = "false"
CONTACT_EMAIL = "admin@localhost"
KUBERNETES_NAMESPACE = ""
JAVA_OPTS = "-Xms256m -Xmx512m"
WILDFLY_EXTRA_OPTS = ""
OVERRIDE_REPORTS_URL = ""
SAVE_REPORTS_ON_DISK = "false"
GOOGLE_PICKER_API_KEY = ""
GOOGLE_PICKER_CLIENT_ID = ""
GOOGLE_PICKER_APP_ID = ""
